### ISSUE TITLE
fix gallery navigation circles

### ISSUE THREAD

**Issue by andrewdacenko** [br-dr/olya-landing-page#13]
Circles should not be shown when zoom is active

![image](https://cloud.githubusercontent.com/assets/2395231/16686425/c454d33a-451a-11e6-9f06-96077afc9485.png)

**Comment by JackLip** [comment]
carousel-indicators has z-index:15
we must assign to .modal z-index>15
.modal {z-index:20} then it will work

**Comment by andrewdacenko** [comment]
@JackLip Better use lover z-index for carousel i.e 1

**Comment by slava89** [comment]
:+1:

**Comment by andrewdacenko** [comment]
commit 840e833  close #13
