### ISSUE TITLE
add contacts section

### ISSUE THREAD

**Issue by slava89** [br-dr/olya-landing-page#28]

**Comment by andrewdacenko** [comment]
@br-dr/brdr please complete it today in order to finish https://github.com/br-dr/olya-landing-page/milestone/1

**Comment by andrewdacenko** [comment]
@slava89 how much time would it take?

**Comment by slava89** [comment]
i will do it today evening/night, but will push it only when i get to this PC tomorrow.

**Comment by andrewdacenko** [comment]
@JackLip can you take this issue and complete earlier?

**Comment by JackLip** [comment]
@br-dr/brdr  yes
